SessionList and SessionListItem components
albonkey/tutor_scheduling pull request #17
Opened 2022-10-11 05:27 UTC by SOLEIGH

adding the SessionList and SessionListItem components

2022-10-12 00:51 UTC, albonkey requested changes
Left a couple comments on things that can be fixed up :)

2022-10-12 00:51 UTC, albonkey commented on src/components/SessionListItem/SessionListItem.module.scss
> +    margin: 10px;
This margin makes the list item not align with the header. Can be removed, and rather use `gap: 10px` in the SessionList.module.scss file.

2022-10-12 00:51 UTC, albonkey commented on src/components/SessionListItem/SessionListItem.js
> +    const [isSelected, setIsSelected] = useState(false);
The isSelected doesnt really do anything here, so no need to include it

2022-10-12 00:51 UTC, albonkey commented on src/components/SessionListItem/SessionListItem.js
> +                    onClick={() => setIsSelected(!isSelected)}
Same for this onclick part here, can be removed, but keep the link just not the onClick part

2022-10-12 00:51 UTC, albonkey commented on src/components/SessionList/SessionList.js
> +			<div className= {style.heading2}>
The code should have different spacing, make sure to only use one tab when nesting divs

2022-10-12 01:46 UTC, SOLEIGH commented on src/components/SessionList/SessionList.js
> +			<div className= {style.heading2}>
I see the spacing issue here, but in the editor it is only one tab for each div. ???

2022-10-13 17:35 UTC, albonkey approved these changes
Looks good, you can go ahead and merge the changes :)

2022-10-13 21:03 UTC, merged